<?php

namespace humhub\modules\flexTheme;

use humhub\modules\flexTheme\helpers\ColorHelper;
use humhub\modules\ui\view\helpers\ThemeHelper;
use Yii;
use yii\helpers\Url;

class Module extends \humhub\components\Module {

    const COLOR_VARS = array('default', 'primary', 'info', 'success', 'warning', 'danger', 'link');
    public $default;
    public $primary;
    public $info;
    public $success;
    public $warning;
    public $danger;
    public $link;
    
    public $background_color_secondary;
    
    // Special colors which were generated by Less functions lighten(), darken() or fade()
    const SPECIAL_COLORS = array(
        'default__darken__2',
        'default__darken__5',
        'default__lighten__2',
        'primary__darken__5',
        'primary__lighten__5',
        'primary__lighten__8',
        'primary__lighten__10',
        'primary__lighten__20',
        'primary__lighten__25',
        'info__darken__5',
        'info__darken__10',
        'info__lighten__5',
        'info__lighten__50',
        'danger__darken__5',
        'danger__lighten__5',
        'success__darken__5',
        'success__lighten__5',
        'warning__darken__2',
        'warning__lighten__5',
        'link__darken__2',
        'link__lighten__5',
        'background_color_secondary__darken__5',
        'warning__fade__25',
        'link__fade__60'
    );
    
    public $default__darken__2;
    public $default__darken__5;
    public $default__lighten__2;
    public $primary__darken__5;
    public $primary__lighten__5;
    public $primary__lighten__8;
    public $primary__lighten__10;
    public $primary__lighten__20;
    public $primary__lighten__25;
    public $info__darken__5;
    public $info__darken__10;
    public $info__lighten__5;
    public $info__lighten__50;
    public $danger__darken__5;
    public $danger__lighten__5;
    public $success__darken__5;
    public $success__lighten__5;
    public $warning__darken__2;
    public $warning__lighten__5;
    public $link__darken__2;
    public $link__lighten__5;
    public $background_color_secondary__darken__5;
    public $warning__fade__25;
    public $link__fade__60;
    
    /*Module settings and their default values*/
    /*@var string defines the style of comment links (options: icon, text, both)*/
    public $commentLink = 'text';
    /*@var string defines the style of like links (options: icon, text, both)*/
    public $likeLink = 'text';
    /*@var string defines the like icon (options: heart, thumbs_up, star)*/
    public $likeIcon = 'thumbs_up';
    /*@var string defines IDs of verified accounts*/
    public $verifiedAccounts = '';
    
    // Translatable Module Description
    public function getDescription() {
        return Yii::t('FlexThemeModule.admin', 'Flexible Theme for HumHub');
    }
    
    // Link to configuration page
    public function getConfigUrl() {
        return Url::to(['/flex-theme/config']);
    }
    
    // Module Activation: Activate Flex Theme
    public function enable() {
        if (parent::enable()) {
            $theme = ThemeHelper::getThemeByName('FlexTheme');
            if ($theme !== null) {
                $theme->activate();
            }
        }
        
        // Save special colors (lightened and darkened colors)
		$special_colors = Module::SPECIAL_COLORS;
		
		foreach ($special_colors as $color) {
			
			list($base_var, $function, $amount) = explode("__", $color);
            
            $theme_var = str_replace('_', '-', $base_var);
            $original_color = $theme->variable($theme_var);
			
			if ($function == 'darken') {
			    $value = ColorHelper::darken($original_color, $amount);
			} elseif ($function == 'lighten') {
		        $value = ColorHelper::lighten($original_color, $amount);
			} elseif ($function == 'fade') {
                $value = ColorHelper::fade($original_color, $amount);
            } elseif ($function == 'fadeout') {
                $value = ColorHelper::fadeout($original_color, $amount);
            }
			
			Yii::$app->getModule('flex-theme')->settings->set($color, $value);
			
		}
    }
	
    // Module Deactivarion: Deselect Flex Theme (activate community theme)
    public function disable() {
        if (Yii::$app->view->theme->name == 'FlexTheme') {
            $theme = ThemeHelper::getThemeByName('HumHub');
            if ($theme !== null) {
                $theme->activate();
            }
        }
	
        parent::disable();
    }
}
