name: PHP Codeception Tests - master

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - '.github/**'
      - '.*'
      - '*.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - '.github/**'
      - '.*'
      - '*.md'

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: flex-theme
      use-rest-module: false
      install-composer: true
